In [1]:
import pandas as pd
import numpy as np

In [3]:
medeq = pd.read_hdf("D:/wsunny/Innovation/2020.7.10 BvD Orbis IP Datafeed For CEIBS/orbisIp_proc/World_medeq_mat_cpc.h5", 
                    key="df")

In [4]:
medeq

,Unnamed: 0,PatPublNr,BvDID_DirectMatch,level,BvDID,Unnamed: 0.1,Company name Latin alphabet,Inactive,Quoted,Branch,...,BvD ID number,cpc_class_symbol,cpc_sequence,CPC_version_date,CPC_section,CPC_class,CPC_subclass,CPC_main_group,CPC_subgroup,CPC_symbol_position
0,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,AU003328176,C12Q 1/6858,0,20130101,C,12,Q,1.0,6858.0,F
1,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,AU003328176,C12Q 1/6883,1,20130101,C,12,Q,1.0,6883.0,L
2,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,AU003328176,C12Q 2600/156,2,20130101,C,12,Q,2600.0,156.0,L
3,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,AU003328176,C12Q 2600/16,3,20130101,C,12,Q,2600.0,16.0,L
4,1,AT214429T,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,AU003328176,C12Q 1/6858,0,20130101,C,12,Q,1.0,6858.0,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10628,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,AU617096652,C12Q 1/6806,18,20130101,C,12,Q,1.0,6806.0,L
10629,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,AU617096652,G01N 33/48,19,20130101,G,1,N,33.0,48.0,L
10630,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,AU617096652,B01L 3/5029,21,20130101,B,1,L,3.0,5029.0,L
10631,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,AU617096652,B01L 2300/0845,22,20130101,B,1,L,2300.0,845.0,L
10632,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,AU617096652,B01L 2300/105,23,20130101,B,1,L,2300.0,105.0,L

In [27]:
medeq['PatPublNr'].nunique()

2815

### Forward Citation

In [5]:
open_pat_fwd_cit = open('D:/wsunny/Innovation/2020.7.10 BvD Orbis IP Datafeed For CEIBS/orbisIp_raw/Patents_ForwardCitations.txt',
         encoding='utf-8', errors='backslashreplace')

In [6]:
pat_fwd_cit = pd.read_table(open_pat_fwd_cit,chunksize=1000000,error_bad_lines=False)

In [7]:
%%time
# select PatPublNr in pat_fwd_cit that matches PatPublNr in join_pat_headers in order to reduce dataframe size

match_pat_fwd_cit = []
for chunks in pat_fwd_cit: 
    chunks.drop_duplicates(keep='first', inplace= True)
    xx = chunks.PatPublNr.isin(medeq.PatPublNr)
    yy = chunks[xx]
    match_pat_fwd_cit.append(yy)

match_pat_fwd_cit_concat = pd.concat(match_pat_fwd_cit)

Wall time: 9min 36s

In [8]:
match_pat_fwd_cit_concat

                PatPublNr  CitingPatPublNr  SeqNr
185145     AU2003273218A1      US9085622B2      1
191437     AU2004298951A1   AU2006273330B2      1
191438     AU2004298951B2      US8852584B2      1
198756     AU2006216732A1      US9085622B2      1
210610     AU2008316319A1     CN107858423A      1
...                   ...              ...    ...
374201505     WO9961880A2      US8816292B2      5
374201506     WO9961880A2      FR2924502A1      6
374201507     WO9961880A2   WO2009071858A3      7
374201508     WO9961880A2  US20160259063A1      8
374201509     WO9961880A2      JP6589047B2      9

[12561 rows x 3 columns]

In [12]:
match_pat_fwd_cit_concat['PatPublNr'].nunique()

928

In [9]:
join_pat_fwd_cit = medeq.merge(match_pat_fwd_cit_concat, how = 'left',on = 'PatPublNr')
join_pat_fwd_cit

,Unnamed: 0,PatPublNr,BvDID_DirectMatch,level,BvDID,Unnamed: 0.1,Company name Latin alphabet,Inactive,Quoted,Branch,...,cpc_sequence,CPC_version_date,CPC_section,CPC_class,CPC_subclass,CPC_main_group,CPC_subgroup,CPC_symbol_position,CitingPatPublNr,SeqNr
0,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,0,20130101,C,12,Q,1.0,6858.0,F,NaN,NaN
1,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,1,20130101,C,12,Q,1.0,6883.0,L,NaN,NaN
2,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,2,20130101,C,12,Q,2600.0,156.0,L,NaN,NaN
3,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,3,20130101,C,12,Q,2600.0,16.0,L,NaN,NaN
4,1,AT214429T,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,0,20130101,C,12,Q,1.0,6858.0,F,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152999,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,18,20130101,C,12,Q,1.0,6806.0,L,NaN,NaN
153000,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,19,20130101,G,1,N,33.0,48.0,L,NaN,NaN
153001,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,21,20130101,B,1,L,3.0,5029.0,L,NaN,NaN
153002,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,22,20130101,B,1,L,2300.0,845.0,L,NaN,NaN
153003,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,23,20130101,B,1,L,2300.0,105.0,L,NaN,NaN

### Backward Citation

In [10]:
pat_bwd_cit = pd.read_table("D:/wsunny/Innovation/2020.7.10 BvD Orbis IP Datafeed For CEIBS/orbisIp_raw/Patents_BackwardCitations.txt", 
                            chunksize = 1000000)

In [11]:
%%time

match_pat_bwd_cit = []
for chunks in pat_bwd_cit: 
    chunks.drop_duplicates(keep='first', inplace = True)
    jj = chunks.PatPublNr.isin(join_pat_fwd_cit.PatPublNr)
    kk = chunks[jj]
    match_pat_bwd_cit.append(kk)

match_pat_bwd_cit_concat = pd.concat(match_pat_bwd_cit)

Wall time: 9min 37s

In [ ]:
match_pat_bwd_cit_concat

In [14]:
match_pat_bwd_cit_concat['PatPublNr'].nunique()

1701

In [12]:
join_pat_bwd_cit = join_pat_fwd_cit.merge(match_pat_bwd_cit_concat, how = 'left',on = 'PatPublNr')
join_pat_bwd_cit

,Unnamed: 0,PatPublNr,BvDID_DirectMatch,level,BvDID,Unnamed: 0.1,Company name Latin alphabet,Inactive,Quoted,Branch,...,CPC_section,CPC_class,CPC_subclass,CPC_main_group,CPC_subgroup,CPC_symbol_position,CitingPatPublNr,SeqNr_x,CitedPatPublNr,SeqNr_y
0,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,C,12,Q,1.0,6858.0,F,NaN,NaN,NaN,NaN
1,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,C,12,Q,1.0,6883.0,L,NaN,NaN,NaN,NaN
2,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,C,12,Q,2600.0,156.0,L,NaN,NaN,NaN,NaN
3,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,C,12,Q,2600.0,16.0,L,NaN,NaN,NaN,NaN
4,1,AT214429T,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,C,12,Q,1.0,6858.0,F,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2340485,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,B,1,L,2300.0,845.0,L,NaN,NaN,US20170159108A1,4.0
2340486,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,B,1,L,2300.0,105.0,L,NaN,NaN,US6299842B1,1.0
2340487,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,B,1,L,2300.0,105.0,L,NaN,NaN,WO2005102526A1,2.0
2340488,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,B,1,L,2300.0,105.0,L,NaN,NaN,WO2011106784A1,3.0
2340489,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,B,1,L,2300.0,105.0,L,NaN,NaN,US20170159108A1,4.0

In [15]:
join_pat_bwd_cit['PatPublNr'].nunique()

2815

In [31]:
col_names_bwd = join_pat_bwd_cit.select_dtypes(include=['object']).columns
col_names_bwd_list = list(col_names_bwd)
col_names_bwd_list

['PatPublNr',
 'BvDID_DirectMatch',
 'BvDID',
 'Company name Latin alphabet',
 'Inactive',
 'Quoted',
 'Branch',
 'OwnData',
 'Woco',
 'Country ISO code',
 'Consolidation code',
 'Operating revenue (Turnover)\nth USD Last avail. yr',
 'Number of employees\nLast avail. yr',
 'Operating revenue (Turnover)\nth USD 2010',
 'BvD ID number',
 'cpc_class_symbol',
 'CPC_section',
 'CPC_subclass',
 'CPC_symbol_position',
 'CitingPatPublNr',
 'CitedPatPublNr']

In [15]:
open_pat_headers = open('D:/wsunny/Innovation/2020.7.10 BvD Orbis IP Datafeed For CEIBS/orbisIp_raw/Patents_Headers.txt',
         encoding='utf-8', errors='backslashreplace')

In [16]:
select_pat_headers = ["PatPublNr","Publn_ctry","GrantDate","Priority_date","Publn_date"]

In [17]:
pat_headers = pd.read_table(open_pat_headers,chunksize=1000000,error_bad_lines=False,usecols = select_pat_headers )

In [18]:
%%time

match_pat_headers = []
for chunks in pat_headers: 
    chunks.drop_duplicates(keep='first', inplace = True)
    m = chunks.PatPublNr.isin(join_pat_bwd_cit.PatPublNr)
    n = chunks[m]
    match_pat_headers.append(n)

match_pat_headers_concat = pd.concat(match_pat_headers)

<decorator-gen-62>:2: DtypeWarning: Columns (43) have mixed types.Specify dtype option on import or set low_memory=False.
<decorator-gen-62>:2: DtypeWarning: Columns (45) have mixed types.Specify dtype option on import or set low_memory=False.

Wall time: 7min 49s

In [19]:
join_pat_headers = join_pat_bwd_cit.merge(match_pat_headers_concat, how = 'left',on = 'PatPublNr')

In [20]:
join_pat_headers

,Unnamed: 0,PatPublNr,BvDID_DirectMatch,level,BvDID,Unnamed: 0.1,Company name Latin alphabet,Inactive,Quoted,Branch,...,CPC_subgroup,CPC_symbol_position,CitingPatPublNr,SeqNr_x,CitedPatPublNr,SeqNr_y,Publn_ctry,Publn_date,GrantDate,Priority_date
0,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,6858.0,F,NaN,NaN,NaN,NaN,AR,1997-11-26,1997-11-26,1995-04-13
1,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,6883.0,L,NaN,NaN,NaN,NaN,AR,1997-11-26,1997-11-26,1995-04-13
2,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,156.0,L,NaN,NaN,NaN,NaN,AR,1997-11-26,1997-11-26,1995-04-13
3,0,AR001619A1,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,16.0,L,NaN,NaN,NaN,NaN,AR,1997-11-26,1997-11-26,1995-04-13
4,1,AT214429T,AU003328176,0,AU003328176,263.0,JOHNSON & JOHNSON RESEARCH PTY LTD,No,No,No,...,6858.0,F,NaN,NaN,NaN,NaN,AT,2002-03-15,2002-03-15,1995-04-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2340485,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,845.0,L,NaN,NaN,US20170159108A1,4.0,WO,2019-12-19,NaN,2018-06-15
2340486,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,105.0,L,NaN,NaN,US6299842B1,1.0,WO,2019-12-19,NaN,2018-06-15
2340487,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,105.0,L,NaN,NaN,WO2005102526A1,2.0,WO,2019-12-19,NaN,2018-06-15
2340488,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,105.0,L,NaN,NaN,WO2011106784A1,3.0,WO,2019-12-19,NaN,2018-06-15
2340489,3882,WO2019237158A1,AU617096652,0,AU617096652,448.0,MICROBA LIFE SCIENCES LIMITED,No,No,No,...,105.0,L,NaN,NaN,US20170159108A1,4.0,WO,2019-12-19,NaN,2018-06-15

In [21]:
join_pat_headers.to_hdf("D:/wsunny/Innovation/2020.7.10 BvD Orbis IP Datafeed For CEIBS/orbisIp_proc/medeq_join_pat_headers.h5", key="df", mode='w')

C:\Users\wsunny\Anaconda3\lib\site-packages\pandas\core\generic.py:2490: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['PatPublNr', 'BvDID_DirectMatch', 'BvDID',
       'Company name Latin alphabet', 'Inactive', 'Quoted', 'Branch',
       'OwnData', 'Woco', 'Country ISO code', 'Consolidation code',
       'Operating revenue (Turnover)\nth USD Last avail. yr',
       'Number of employees\nLast avail. yr',
       'Operating revenue (Turnover)\nth USD 2010', 'BvD ID number',
       'cpc_class_symbol', 'CPC_section', 'CPC_subclass',
       'CPC_symbol_position', 'CitingPatPublNr', 'CitedPatPublNr',
       'Publn_ctry', 'Publn_date', 'GrantDate', 'Priority_date'],
      dtype='object')]

  pytables.to_hdf(

In [50]:
medeq_bwd_fwd_cit_numeric = join_pat_bwd_cit.pivot_table(index=['PatPublNr','BvDID','Company name Latin alphabet'])
medeq_bwd_fwd_cit_numeric

,,,CPC_class,CPC_main_group,CPC_subgroup,CPC_version_date,Last avail. year,"NACE Rev. 2, core code (4 digits)",SeqNr_x,SeqNr_y,Unnamed: 0,Unnamed: 0.1,cpc_sequence,level
PatPublNr,BvDID,Company name Latin alphabet,,,,,,,,,,,,
AR001619A1,AU003328176,JOHNSON & JOHNSON RESEARCH PTY LTD,12.0,1300.500000,3478.250000,2.013010e+07,2015.0,8690,NaN,NaN,0,263.0,1.5,0.0
AT214429T,AU003328176,JOHNSON & JOHNSON RESEARCH PTY LTD,12.0,1300.500000,3478.250000,2.013010e+07,2015.0,8690,NaN,NaN,1,263.0,1.5,0.0
AT275443T,JP8140001024530,MICRON INC.,33.5,9.000000,19.000000,2.013010e+07,2019.0,8690,NaN,NaN,405,134.0,0.5,0.0
AT303106T,JP8140001024530,MICRON INC.,61.0,6.333333,15.333333,2.013010e+07,2019.0,8690,NaN,NaN,406,134.0,1.0,0.0
AT309527T,AU120974692,CLINICAL GENOMICS TECHNOLOGIES PTY LTD,13.0,500.000000,5551.636364,2.014466e+07,2018.0,8690,NaN,NaN,587,138.0,5.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZA7701303A,KR1101112077661,METABIO INC,43.0,189.000000,2.666667,2.016343e+07,2014.0,8690,NaN,NaN,3148,465.0,1.0,0.0
ZA7704607A,KR1101112077661,METABIO INC,35.5,272.500000,528.500000,2.013010e+07,2014.0,8690,NaN,NaN,3149,465.0,0.5,0.0
ZA9602941A,AU003328176,JOHNSON & JOHNSON RESEARCH PTY LTD,12.0,1300.500000,3478.250000,2.013010e+07,2015.0,8690,NaN,NaN,402,263.0,1.5,0.0
ZA9901772A,AU003328176,JOHNSON & JOHNSON RESEARCH PTY LTD,12.0,1.000000,5814.833333,2.013010e+07,2015.0,8690,NaN,NaN,403,263.0,2.5,0.0
ZA9902374A,AU003328176,JOHNSON & JOHNSON RESEARCH PTY LTD,12.0,1.000000,5305.250000,2.013010e+07,2015.0,8690,NaN,NaN,404,263.0,1.5,0.0

In [51]:
medeq_bwd_fwd_cit_numeric.to_hdf("D:/wsunny/NLP Project/2020.7.10 BvD Orbis IP Datafeed For CEIBS/orbisIp_proc/medeq_bwd_fwd_cit_numeric.h5", key="df", mode='w')

C:\Users\wsunny\Anaconda3\lib\site-packages\tables\attributeset.py:464: NaturalNameWarning: object name is not a valid Python identifier: 'axis1_nameCompany name Latin alphabet'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

In [28]:
car = pd.read_hdf("D:/wsunny/NLP Project/2020.7.10 BvD Orbis IP Datafeed For CEIBS/orbisIp_proc/US_car_mat_cpc.h5", 
                    key="df")